### ISSUE TITLE
Add option to append text/markup

### ISSUE THREAD

**Issue by missmatsuko** [remarkjs/remark-external-links#11]
For [WCAG compliance](https://www.w3.org/TR/WCAG20-TECHS/G201.html), can we add an option to add text/markup after the link content?

**Comment by wooorm** [comment]
Oh I like that idea! It would have to be content instead of a string though, as we’d otherwise have to include the remark parser again and that would be too heavy probably.

Would be similar also to [remark-autolink-headings’ `content` option](https://github.com/remarkjs/remark-autolink-headings#optionscontent).

Are you able and interested in working on this?

**Comment by missmatsuko** [comment]
> Oh I like that idea! It would have to be content instead of a string though, as we’d otherwise have to include the remark parser again and that would be too heavy probably.

Just for my own sake, would you mind explaining why adding text would require the remark parser twice? I think content would be a better option anyways, since it could then be styled.

> Are you able and interested in working on this?

Definitely interested! I will take a closer look tonight, but it does seem pretty straight-forward, especially with `remark-autolink-headings` as a reference. Thanks!

**Comment by wooorm** [comment]
> Just for my own sake, would you mind explaining why adding text would require the remark parser twice? I think content would be a better option anyways, since it could then be styled.

To begin: we’re working with remark/mdast, so we’re working with markdown in this context. Not html/rehype/hast. So the options are `markdown *is* cool` vs `[{type: 'text', value: 'markdown'}, {type: 'emphasis', children: [{type: 'text', value: 'is'}]}, {type: 'text', value: 'cool'}]`. What I mean by content is the latter, where a string is the former. Having a string would need to include remark-parse somehow to parse the string to the content / tree. Having remark-parse typically wouldn’t be a problem, because dependencies are only included once in bundles/node, but for cases where someone does not use remark-parse themselves, because they send the virtual tree from a server or because of some other reason, would add a big lot of code/size in the bundle. Which is unneeded for users!

> Definitely interested! I will take a closer look tonight, but it does seem pretty straight-forward, especially with remark-autolink-headings as a reference. Thanks!

Oh that’s cool Matsuko! Great, let me know if I can help!

**Comment by iloveip** [comment]
Hi @wooorm and @missmatsuko ,

Could you please give an example of using `content` option with React component? For example, how can I define `content`, if I need to use something like `<IconFont type="icon-external-link" />`?

**Comment by wooorm** [comment]
Something like:

```js
var externalLinks = require('remark-external-links')
var s = require('hastscript/svg')

// …
.use(externalLinks, {
  target: false,
  rel: ['nofollow'],
  content: s('svg', {xmlns: 'http://www.w3.org/2000/svg', viewbox: '0 0 500 500'}, [
    s('title', 'SVG `<circle>` element'),
    s('circle', {cx: 120, cy: 120, r: 100})
  ])
})
// …
```

Please in the future don’t comment on old issues. Questions can go on Spectrum

**Comment by iloveip** [comment]
@wooorm Thank you very much!
